<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE actions [
	<!ELEMENT actions (action+)>
	<!ELEMENT action (icon?,name,regex,commands)>
	<!ELEMENT commands (command+)>
	<!ELEMENT command (name,exec)>

	<!ELEMENT icon (#PCDATA)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT regex (#PCDATA)>
	<!ELEMENT exec (#PCDATA)>
]>
<actions>
	<action>
		<name>Image</name>
		<regex>(/|http|ftp).+\.(jpg|png|gif)</regex>
		<commands>
			<command>
				<name>View with Ristretto</name>
				<exec>ristretto \0</exec>
			</command>
			<command>
				<name>Edit with Gimp</name>
				<exec>gimp \0</exec>
			</command>
		</commands>
	</action>
	<action>
		<name>Bugz</name>
		<regex>.*(bug #|bug |Bug #|Bug )([0-9]+).*</regex>
		<commands>
			<command>
				<name>Xfce Bug</name>
				<exec>exo-open http://bugzilla.xfce.org/show_bug.cgi?id=\2</exec>
			</command>
			<command>
				<name>GNOME Bug</name>
				<exec>exo-open http://bugzilla.gnome.org/show_bug.cgi?id=\2</exec>
			</command>
		</commands>
	</action>
</actions>
